# Generated by Django 3.0.8 on 2020-07-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='emailid',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
